---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/stores":
    get:
      summary: Retrieves Stores
      description: Retrieves all the stores
      responses:
        '200':
          description: Stores retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  address:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
                required:
                - id
                - name
                - address
                - email
                - phone
    post:
      summary: Creates Store
      description: Creates Store
      parameters: []
      responses:
        '201':
          description: stote created
  "/api/v1/stores/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Retrieves Store
      responses:
        '200':
          description: store retrieved
          content:
            application/json:
              schema:
                "$ref": "#/definitions/store_resource"
        '404':
          description: invalid store id
    put:
      summary: Updates Store
      description: Updates Store
      parameters: []
      responses:
        '200':
          description: store updated
    delete:
      summary: Deletes Store
      description: Deletes specific store
      responses:
        '204':
          description: store deleted
        '404':
          description: store not found
servers:
- url: http://{defaultHost}:3000
  variables:
    defaultHost:
      default: localhost
