---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/products":
    get:
      summary: Retrieves Products
      description: Retrieves all the products
      responses:
        '200':
          description: Products retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    sku:
                      type: string
                    product_type:
                      type: string
                    price:
                      type: float
    post:
      summary: Creates Product
      description: Creates Product
      parameters: []
      responses:
        '201':
          description: stote created
  "/api/v1/products/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Show Product
      responses:
        '200':
          description: product retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  sku:
                    type: string
                  product_type:
                    type: string
                  price:
                    type: float
        '404':
          description: invalid product id
    put:
      summary: Updates product
      description: Updates product
      parameters: []
      responses:
        '200':
          description: product updated
    delete:
      summary: Deletes product
      description: Deletes specific product
      responses:
        '204':
          description: product deleted
        '404':
          description: product not found
  "/api/v1/stores":
    get:
      summary: Retrieves Stores
      description: Retrieves all the stores
      responses:
        '200':
          description: Stores retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    address:
                      type: string
                    email:
                      type: string
                    phone:
                      type: string
    post:
      summary: Creates Store
      description: Creates Store
      parameters: []
      responses:
        '201':
          description: stote created
  "/api/v1/stores/{id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Show Store
      responses:
        '200':
          description: store retrieved
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  address:
                    type: string
                  email:
                    type: string
                  phone:
                    type: string
        '404':
          description: invalid store id
    put:
      summary: Updates Store
      description: Updates Store
      parameters: []
      responses:
        '200':
          description: store updated
    delete:
      summary: Deletes Store
      description: Deletes specific store
      responses:
        '204':
          description: store deleted
        '404':
          description: store not found
  "/api/v1/stores/{id}/products":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    get:
      summary: Show Store products
      responses:
        '200':
          description: Products retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    sku:
                      type: string
                    product_type:
                      type: string
                    price:
                      type: float
        '404':
          description: invalid store id
  "/api/v1/stores/{id}/add_product/{product_id}":
    parameters:
    - name: id
      in: path
      required: true
      schema:
        type: integer
    - name: product_id
      in: path
      required: true
      schema:
        type: integer
    post:
      summary: Add product to store
      responses:
        '200':
          description: Products retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    sku:
                      type: string
                    product_type:
                      type: string
                    price:
                      type: float
        '404':
          description: invalid store id
servers:
- url: http://{defaultHost}:35794
  variables:
    defaultHost:
      default: localhost
